### PR TITLE
Analyze how met data drive calculated disturbance metrics

### PR DESCRIPTION
**Pull request by bpbond**
This PR adds a standalone `metric_analysis.Rmd` file (didn't integrate it into your drake pipeline, sorry) that analyzes the relationship between disturbance metrics and their meteorological inputs. The code:
* looks for autocorrelation among the met variables and removes a few
* fits Random Forest models for each variable (GPP, NPP, NEP, and Rh) and metric, and 
* produces plots showing variable importance and partial dependence of the most important met variables for each output variable.

I have posted the Rmd output here: https://rpubs.com/bpbond/775538

### CODE REVIEW

**Review by kdorheim — APPROVED** [review]
Hi Ben I think it looks good! And I also don't have any of the paper analysis in the drake workflow. Here drake has been really helpful in setting up the workflow to go from these ED output things --> time series of flux data we at a scale we care about --> the metrics. 

I would like to talk through the markdown during our next meeting thouh, I've got questions.

**Comment by bpbond** [comment]
Sounds good! 👍

**Comment by bpbond** [comment]
Interestingly, this Rmd errors (in one of the `split` commands) under R 3.6. Under R 4.1, it works.

**Comment by bpbond** [comment]
@kdorheim I have updated the manuscript with variable importance plots, based on f73d85f.

**Comment by kdorheim** [comment]
great thanks!

**Pull request merged**
